version: '2.1'

services:
    users-db:
        container_name: user_db
        build: ./app/db
        ports:
            - 5435:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        healthcheck:
            test: exit 0

    users-service:
        container_name: users_service
        build: ./
        ports:
            - 5001:5000
        environment:
            - APP_SETTINGS=app.config.DevelopmentConfig
            - DEV_DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
            - TEST_DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_test
            - SECRET_KEY='db84456420fddaf133f2418ef219f7ca11e35d6650220ae9'
            - SITE_ADMIN=tomnolan95@gmail.com
            - MAIL_PASSWORD=hxupokqhmpuyrguz
        depends_on:
            users-db:
                condition: service_healthy
        links:
            - users-db

    nginx:
        container_name: nginx
        build: ./app/nginx/
        restart: always
        ports:
            - 80:80
        depends_on:
            users-service:
                condition: service_started
        links:
            - users-service